# param_data.py

from dataclasses import dataclass, field
import copy

@dataclass
class Parameter:
    name: str
    value: float
    units: str
    options: str
    desc: str
    group: str = ""
    type: str = "FLOAT"
    min_val: str = ""
    max_val: str = ""
    modified: bool = False
    favourite: bool = False

DEFAULT_PARAMS = [
    # ── UAVCAN Motor Parameters ──────────────────────────────────────
    Parameter("ctl_bw",        75,      "Hz",     "10 250",   "Speed controller bandwidth. Higher values = faster response but may overshoot.", "UAVCAN Motor Parameters", "INT32"),
    Parameter("ctl_dir",       1,       "",       "0 1",       "Motor spin direction. Use 0 or 1 to reverse direction.", "UAVCAN Motor Parameters", "INT32"),
    Parameter("ctl_gain",      1.0,     "A*s/rad","0.00 1.00", "Speed (RPM) controller gain. Higher = faster response but may oscillate.", "UAVCAN Motor Parameters", "FLOAT"),
    Parameter("ctl_hz_idle",   3.5,     "Hz",     "0.0 100.0", "Idle speed in electrical Hz.", "UAVCAN Motor Parameters", "FLOAT"),
    Parameter("ctl_start_rate",25,      "Hz/s",   "5 1000",    "Spin-up rate in electrical Hz per second.", "UAVCAN Motor Parameters", "INT32"),
    Parameter("esc_index",     0,       "Index",  "0 15",      "Index of this ESC in throttle command messages.", "UAVCAN Motor Parameters", "INT32"),
    Parameter("id_ext_status", 20034,   "",       "1 1000000", "Extended status ID.", "UAVCAN Motor Parameters", "INT32"),
    Parameter("int_ext_status",50000,   "µs",     "0 1000000", "Extended status interval in microseconds.", "UAVCAN Motor Parameters", "INT32"),
    Parameter("int_status",    50000,   "µs",     "0 1000000", "ESC status interval in microseconds.", "UAVCAN Motor Parameters", "INT32"),
    Parameter("mot_i_max",     12,      "A",      "1 80",      "Motor current limit in amps. Set to continuous current rating from motor spec sheet.", "UAVCAN Motor Parameters", "FLOAT"),
    Parameter("mot_kv",        2300,    "RPM/V",  "0 4000",    "Motor Kv in RPM per volt. Taken from motor specification sheet.", "UAVCAN Motor Parameters", "INT32"),
    Parameter("mot_ls",        0.0,     "H",      "",          "READ ONLY: Motor inductance in henries. Measured on start-up.", "UAVCAN Motor Parameters", "FLOAT"),
    Parameter("mot_num_poles", 14,      "Poles",  "2 40",      "Number of motor poles. Used to convert mechanical to electrical speeds.", "UAVCAN Motor Parameters", "INT32"),
    Parameter("mot_rs",        0.0,     "Ohm",    "",          "READ ONLY: Motor resistance in ohms. Measured on start-up.", "UAVCAN Motor Parameters", "FLOAT"),
    Parameter("mot_v_accel",   0.5,     "V",      "0.01 1.00", "Acceleration limit in volts.", "UAVCAN Motor Parameters", "FLOAT"),
    Parameter("mot_v_max",     14.8,    "V",      "0+",        "Motor voltage limit. Controller commanded voltage will never exceed this.", "UAVCAN Motor Parameters", "FLOAT"),

    # ── Attitude EKF estimator ───────────────────────────────────────
    Parameter("EKF_ATT_V3_Q0", 1e-4,   "",       "",          "Body angular rate process noise.", "Attitude EKF estimator", "FLOAT"),
    Parameter("EKF_ATT_V3_Q1", 0.08,   "",       "",          "Body angular acceleration process noise.", "Attitude EKF estimator", "FLOAT"),
    Parameter("EKF_ATT_V3_Q2", 0.009,  "",       "",          "Acceleration process noise.", "Attitude EKF estimator", "FLOAT"),
    Parameter("EKF_ATT_V3_Q3", 0.005,  "",       "",          "Magnet field vector process noise.", "Attitude EKF estimator", "FLOAT"),
    Parameter("EKF_ATT_V4_R0", 0.0008, "",       "",          "Gyro measurement noise.", "Attitude EKF estimator", "FLOAT"),
    Parameter("EKF_ATT_V4_R1", 10000.0,"",       "",          "Accel measurement noise.", "Attitude EKF estimator", "FLOAT"),
    Parameter("EKF_ATT_V4_R2", 100.0,  "",       "",          "Mag measurement noise.", "Attitude EKF estimator", "FLOAT"),
    Parameter("ATT_J11",       0.0018, "kg*m^2", "",          "Moment of inertia matrix diagonal entry (1,1).", "Attitude EKF estimator", "FLOAT"),
    Parameter("ATT_J22",       0.0018, "kg*m^2", "",          "Moment of inertia matrix diagonal entry (2,2).", "Attitude EKF estimator", "FLOAT"),
    Parameter("ATT_J33",       0.0037, "kg*m^2", "",          "Moment of inertia matrix diagonal entry (3,3).", "Attitude EKF estimator", "FLOAT"),
    Parameter("ATT_J_EN",      0,      "",       "0 1",       "If != 0, moment of inertia will be used in the estimator.", "Attitude EKF estimator", "INT32"),

    # ── Attitude Q estimator ─────────────────────────────────────────
    Parameter("ATT_W_ACC",       0.2,  "",       "0 1",       "Complementary filter accelerometer weight.", "Attitude Q estimator", "FLOAT"),
    Parameter("ATT_W_MAG",       0.1,  "",       "0 1",       "Complementary filter magnetometer weight.", "Attitude Q estimator", "FLOAT"),
    Parameter("ATT_W_EXT_HDG",   0.1,  "",       "0 1",       "Complementary filter external heading weight.", "Attitude Q estimator", "FLOAT"),
    Parameter("ATT_W_GYRO_BIAS", 0.1,  "",       "0 1",       "Complementary filter gyroscope bias weight.", "Attitude Q estimator", "FLOAT"),
    Parameter("ATT_MAG_DECL",    0.0,  "deg",    "",          "Magnetic declination in degrees. Not used in normal operation (GPS lookup used).", "Attitude Q estimator", "FLOAT"),
    Parameter("ATT_MAG_DECL_A",  1,    "",       "0 1",       "Enable automatic GPS based declination compensation.", "Attitude Q estimator", "INT32"),
    Parameter("ATT_EXT_HDG_M",   0,    "",       "0 2",       "External heading mode. 1=Vision, 2=Motion capture.", "Attitude Q estimator", "INT32"),
    Parameter("ATT_ACC_COMP",    2,    "",       "1 2",       "Enable acceleration compensation based on GPS velocity.", "Attitude Q estimator", "INT32"),
    Parameter("ATT_BIAS_MAX",    0.05, "rad/s",  "0 2",       "Gyro bias limit.", "Attitude Q estimator", "FLOAT"),
    Parameter("ATT_VIBE_THRESH", 0.2,  "",       "0.01 10",   "Threshold (RMS) to warn about high vibration levels.", "Attitude Q estimator", "FLOAT"),

    # ── Battery Calibration ──────────────────────────────────────────
    Parameter("BAT_V_EMPTY",    3.4,   "V",      "",          "Empty cell voltage. Voltage where a single cell is considered empty.", "Battery Calibration", "FLOAT"),
    Parameter("BAT_V_CHARGED",  4.2,   "V",      "",          "Full cell voltage. Voltage where a single cell is considered full.", "Battery Calibration", "FLOAT"),
    Parameter("BAT_V_LOAD_DROP",0.07,  "V",      "0.0 1.5",   "Voltage drop per cell on 100% load. Implicitly defines internal resistance to max current ratio.", "Battery Calibration", "FLOAT"),
    Parameter("BAT_N_CELLS",    3,     "S",      "2 10",      "Number of cells the attached battery consists of.", "Battery Calibration", "INT32"),
    Parameter("BAT_CAPACITY",   -1.0,  "mAh",    "-1.0 100000","Battery capacity in mAh. Set to -1 to disable.", "Battery Calibration", "FLOAT"),
    Parameter("BAT_V_SCALE_IO", 10000, "",       "1 100000",  "Scaling factor for battery voltage sensor on PX4IO.", "Battery Calibration", "INT32"),
    Parameter("BAT_V_SCALING",  -1.0,  "",       "",          "Scaling factor for battery voltage sensor on FMU v2.", "Battery Calibration", "FLOAT"),
    Parameter("BAT_C_SCALING",  -1.0,  "",       "",          "Scaling factor for battery current sensor.", "Battery Calibration", "FLOAT"),

    # ── Camera trigger ───────────────────────────────────────────────
    Parameter("TRIG_INTERVAL",  40.0,  "ms",     "4.0 10000.0","Time between two consecutive trigger events.", "Camera trigger", "FLOAT"),
    Parameter("TRIG_POLARITY",  0,     "",       "0 1",        "Camera trigger polarity. 0=ACTIVE_LOW, 1=ACTIVE_HIGH.", "Camera trigger", "INT32"),
    Parameter("TRIG_ACT_TIME",  0.5,   "ms",     "",           "Time the trigger needs to be pulled high or low.", "Camera trigger", "FLOAT"),
    Parameter("TRIG_MODE",      0,     "",       "0 4",        "Camera trigger mode. 0=off, 1=cmd, 2=always, 3=distance, 4=distance+cmd.", "Camera trigger", "INT32"),
    Parameter("TRIG_PINS",      12,    "",       "1 123456",   "Camera trigger pin. Selects which AUX pin is used (AUX1-AUX6).", "Camera trigger", "INT32"),
    Parameter("TRIG_DISTANCE",  25.0,  "m",      "0+",         "Distance at which to trigger the camera.", "Camera trigger", "FLOAT"),

    # ── Circuit Breaker ──────────────────────────────────────────────
    Parameter("CBRK_SUPPLY_CHK", 0,    "",       "0 894281",   "Circuit breaker for power supply check. Set 894281 to disable. WARNING: OWN RISK.", "Circuit Breaker", "INT32"),
    Parameter("CBRK_RATE_CTRL",  0,    "",       "0 140253",   "Circuit breaker for rate controller output. Set 140253 to disable. WARNING: OWN RISK.", "Circuit Breaker", "INT32"),
    Parameter("CBRK_IO_SAFETY",  0,    "",       "0 22027",    "Circuit breaker for IO safety. Set 22027 to disable. WARNING: OWN RISK.", "Circuit Breaker", "INT32"),
    Parameter("CBRK_AIRSPD_CHK", 0,    "",       "0 162128",   "Circuit breaker for airspeed sensor check. Set 162128 to disable. WARNING: OWN RISK.", "Circuit Breaker", "INT32"),
    Parameter("CBRK_FLIGHTTERM", 121212,"",      "0 121212",   "Circuit breaker for flight termination. Set 121212 to disable. WARNING: OWN RISK.", "Circuit Breaker", "INT32"),
    Parameter("CBRK_ENGINEFAIL", 284953,"",      "0 284953",   "Circuit breaker for engine failure detection. WARNING: OWN RISK.", "Circuit Breaker", "INT32"),
    Parameter("CBRK_GPSFAIL",   240024, "",      "0 240024",   "Circuit breaker for GPS failure detection. WARNING: OWN RISK.", "Circuit Breaker", "INT32"),
    Parameter("CBRK_BUZZER",    0,     "",       "0 782097",   "Circuit breaker to disable buzzer. Set 782097 to disable. WARNING: OWN RISK.", "Circuit Breaker", "INT32"),
    Parameter("CBRK_USB_CHK",   0,     "",       "0 197848",   "Circuit breaker for USB link check. Set 197848 to disable. WARNING: OWN RISK.", "Circuit Breaker", "INT32"),

    # ── Commander ────────────────────────────────────────────────────
    Parameter("COM_DL_LOSS_EN",  0,    "",       "0:OFF 1:ON", "Datalink loss mode enabled. 1=enable failsafe actions on datalink loss.", "Commander", "INT32"),
    Parameter("COM_DL_LOSS_T",   10,   "s",      "0 30",       "Datalink loss time threshold in seconds.", "Commander", "INT32"),
    Parameter("COM_DL_REG_T",    0,    "s",      "0 30",       "Datalink regain time threshold in seconds.", "Commander", "INT32"),
    Parameter("COM_EF_THROT",    0.5,  "",       "0.0 1.0",    "Engine Failure Throttle Threshold. Triggers only above this throttle value.", "Commander", "FLOAT"),
    Parameter("COM_EF_C2T",      5.0,  "A",      "0.0 50.0",   "Engine Failure Current/Throttle Threshold.", "Commander", "FLOAT"),
    Parameter("COM_EF_TIME",     10.0, "s",      "0.0 60.0",   "Engine Failure Time Threshold in seconds.", "Commander", "FLOAT"),
    Parameter("COM_RC_LOSS_T",   0.5,  "s",      "0 35",       "RC loss time threshold. After this many seconds without RC the rc lost flag is set.", "Commander", "FLOAT"),
    Parameter("COM_HOME_H_T",    5.0,  "m",      "2 15",       "Home set horizontal threshold in meters.", "Commander", "FLOAT"),
    Parameter("COM_HOME_V_T",    10.0, "m",      "5 25",       "Home set vertical threshold in meters.", "Commander", "FLOAT"),
    Parameter("COM_AUTOS_PAR",   1,    "",       "0:Disabled 1:Enabled", "Autosaving of params. Commander auto-saves params to persistent storage on change.", "Commander", "INT32"),
    Parameter("COM_RC_IN_MODE",  0,    "",       "0:RC Transmitter 1:Disable RC 2:Virtual RC", "RC control input mode.", "Commander", "INT32"),
    Parameter("COM_DISARM_LAND", 0,    "s",      "0 20",       "Time-out for auto disarm after landing. 0=disabled.", "Commander", "INT32"),

    # ── Data Link Loss ───────────────────────────────────────────────
    Parameter("NAV_DLL_CH_T",   120.0, "s",      "0.0+",       "Comms hold wait time in seconds.", "Data Link Loss", "FLOAT"),
    Parameter("NAV_DLL_CH_LAT",-266072120,"deg*1e7","−900000000 900000000","Comms hold waypoint latitude.", "Data Link Loss", "INT32"),
    Parameter("NAV_DLL_CH_LON",1518453890,"deg*1e7","-1800000000 1800000000","Comms hold waypoint longitude.", "Data Link Loss", "INT32"),
    Parameter("NAV_DLL_CH_ALT", 600.0, "m",      "-50 30000",  "Comms hold waypoint altitude.", "Data Link Loss", "FLOAT"),
    Parameter("NAV_DLL_AH_T",   120.0, "s",      "0.0+",       "Airfield home wait time in seconds.", "Data Link Loss", "FLOAT"),
    Parameter("NAV_DLL_N",      2,     "",       "0 1000",     "Number of allowed datalink timeouts before direct RTH.", "Data Link Loss", "INT32"),
    Parameter("NAV_DLL_CHSK",   0,     "",       "0 1",        "Skip comms hold wp on data link loss and fly directly to airfield home.", "Data Link Loss", "INT32"),
    Parameter("NAV_AH_LAT",    -265847810,"deg*1e7","-900000000 900000000","Airfield home waypoint latitude.", "Data Link Loss", "INT32"),
    Parameter("NAV_AH_LON",    1518423250,"deg*1e7","-1800000000 1800000000","Airfield home waypoint longitude.", "Data Link Loss", "INT32"),
    Parameter("NAV_AH_ALT",     600.0, "m",      "-50+",       "Airfield home waypoint altitude.", "Data Link Loss", "FLOAT"),

    # ── EKF2 ─────────────────────────────────────────────────────────
    Parameter("EKF2_MAG_DELAY",  0,    "ms",     "0 300",      "Magnetometer measurement delay relative to IMU measurements.", "EKF2", "FLOAT"),
    Parameter("EKF2_BARO_DELAY", 0,    "ms",     "0 300",      "Barometer measurement delay relative to IMU measurements.", "EKF2", "FLOAT"),
    Parameter("EKF2_GPS_DELAY",  200,  "ms",     "0 300",      "GPS measurement delay relative to IMU measurements.", "EKF2", "FLOAT"),
    Parameter("EKF2_ASP_DELAY",  200,  "ms",     "0 300",      "Airspeed measurement delay relative to IMU measurements.", "EKF2", "FLOAT"),
    Parameter("EKF2_GPS_CHECK",  21,   "",       "0 511",      "Integer bitmask controlling GPS checks. Set bits to 1 to enable checks.", "EKF2", "INT32"),
    Parameter("EKF2_REQ_EPH",    5.0,  "m",      "2 100",      "Required EPH to use GPS.", "EKF2", "FLOAT"),
    Parameter("EKF2_REQ_EPV",    8.0,  "m",      "2 100",      "Required EPV to use GPS.", "EKF2", "FLOAT"),
    Parameter("EKF2_REQ_SACC",   1.0,  "m/s",    "0.5 5.0",    "Required speed accuracy to use GPS.", "EKF2", "FLOAT"),
    Parameter("EKF2_REQ_NSATS",  6,    "",       "4 12",       "Required satellite count to use GPS.", "EKF2", "INT32"),
    Parameter("EKF2_REQ_GDOP",   2.5,  "",       "1.5 5.0",    "Required GDoP to use GPS.", "EKF2", "FLOAT"),
    Parameter("EKF2_REQ_HDRIFT", 0.3,  "m/s",    "0.1 1.0",    "Maximum horizontal drift speed to use GPS.", "EKF2", "FLOAT"),
    Parameter("EKF2_REQ_VDRIFT", 0.5,  "m/s",    "0.1 1.5",    "Maximum vertical drift speed to use GPS.", "EKF2", "FLOAT"),
    Parameter("EKF2_GYR_NOISE",  1e-3, "rad/s",  "0.0001 0.01","Rate gyro noise for covariance prediction.", "EKF2", "FLOAT"),
    Parameter("EKF2_ACC_NOISE",  0.25, "m/s/s",  "0.01 1.0",   "Accelerometer noise for covariance prediction.", "EKF2", "FLOAT"),
    Parameter("EKF2_GYR_B_NOISE",7e-5, "rad/s",  "0.0 0.0001", "Process noise for delta angle bias prediction.", "EKF2", "FLOAT"),
    Parameter("EKF2_ACC_B_NOISE",1e-4, "m/s/s",  "0.0 0.01",   "Process noise for delta velocity z bias prediction.", "EKF2", "FLOAT"),
    Parameter("EKF2_GYR_S_NOISE",3e-3, "",       "0.0 0.01",   "Process noise for delta angle scale factor prediction.", "EKF2", "FLOAT"),
    Parameter("EKF2_MAG_B_NOISE",2.5e-2,"Gauss/s","0.0 0.1",   "Process noise for sensor bias and earth magnetic field prediction.", "EKF2", "FLOAT"),
    Parameter("EKF2_WIND_NOISE", 1e-1, "m/s/s",  "0.0 1.0",    "Process noise for wind velocity prediction.", "EKF2", "FLOAT"),
    Parameter("EKF2_GPS_V_NOISE",0.5,  "m/s",    "0.01 5.0",   "Measurement noise for GPS horizontal velocity.", "EKF2", "FLOAT"),
    Parameter("EKF2_GPS_P_NOISE",1.0,  "m",      "0.01 10.0",  "Measurement noise for GPS position.", "EKF2", "FLOAT"),
    Parameter("EKF2_NOAID_NOISE",10.0, "m",      "0.5 50.0",   "Measurement noise for non-aiding position hold.", "EKF2", "FLOAT"),
    Parameter("EKF2_BARO_NOISE", 3.0,  "m",      "0.01 15.0",  "Measurement noise for barometric altitude.", "EKF2", "FLOAT"),
    Parameter("EKF2_HEAD_NOISE", 0.17, "rad",     "0.01 1.0",   "Measurement noise for magnetic heading fusion.", "EKF2", "FLOAT"),
    Parameter("EKF2_MAG_NOISE",  5e-2, "Gauss",  "0.001 1.0",  "Measurement noise for magnetometer 3-axis fusion.", "EKF2", "FLOAT"),
    Parameter("EKF2_MAG_DECL",   0,    "deg",    "",            "Magnetic declination in degrees.", "EKF2", "FLOAT"),
    Parameter("EKF2_HDG_GATE",   3.0,  "SD",     "1.0+",       "Gate size for magnetic heading fusion.", "EKF2", "FLOAT"),
    Parameter("EKF2_MAG_GATE",   3.0,  "SD",     "1.0+",       "Gate size for magnetometer XYZ component fusion.", "EKF2", "FLOAT"),
    Parameter("EKF2_DECL_TYPE",  7,    "",       "0 7",        "Bitmask controlling handling of magnetic declination.", "EKF2", "INT32"),
    Parameter("EKF2_MAG_TYPE",   0,    "",       "0 2",        "Magnetometer fusion type. 0=auto, 1=heading, 2=3-axis.", "EKF2", "INT32"),
    Parameter("EKF2_BARO_GATE",  3.0,  "SD",     "1.0+",       "Gate size for barometric height fusion.", "EKF2", "FLOAT"),
    Parameter("EKF2_GPS_P_GATE", 3.0,  "SD",     "1.0+",       "Gate size for GPS horizontal position fusion.", "EKF2", "FLOAT"),
    Parameter("EKF2_GPS_V_GATE", 3.0,  "SD",     "1.0+",       "Gate size for GPS velocity fusion.", "EKF2", "FLOAT"),
    Parameter("EKF2_REC_RPL",    0,    "",       "0 1",        "If 1, ekf2 module will publish replay messages for logging.", "EKF2", "INT32"),

    # ── FW Attitude Control ──────────────────────────────────────────
    Parameter("FW_R_TC",         0.4,  "s",      "0.4 1.0",    "Attitude Roll Time Constant.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_P_TC",         0.4,  "s",      "0.2 1.0",    "Attitude Pitch Time Constant.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_PR_P",         0.08, "",       "0.005 1.0",  "Pitch rate proportional gain.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_PR_I",         0.02, "",       "0.005 0.5",  "Pitch rate integrator gain.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_P_RMAX_POS",   60.0, "deg/s",  "0.0 90.0",   "Maximum positive (up) pitch rate.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_P_RMAX_NEG",   60.0, "deg/s",  "0.0 90.0",   "Maximum negative (down) pitch rate.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_PR_IMAX",      0.4,  "",       "0.0 1.0",    "Pitch rate integrator limit.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_RR_P",         0.05, "",       "0.005 1.0",  "Roll rate proportional gain.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_RR_I",         0.01, "",       "0.005 0.2",  "Roll rate integrator gain.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_RR_IMAX",      0.2,  "",       "0.0 1.0",    "Roll integrator anti-windup limit.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_R_RMAX",       70.0, "deg/s",  "0.0 90.0",   "Maximum roll rate.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_YR_P",         0.05, "",       "0.005 1.0",  "Yaw rate proportional gain.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_YR_I",         0.0,  "",       "0.0 50.0",   "Yaw rate integrator gain.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_YR_IMAX",      0.2,  "",       "0.0 1.0",    "Yaw rate integrator limit.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_Y_RMAX",       0.0,  "deg/s",  "0.0 90.0",   "Maximum yaw rate.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_WR_P",         0.5,  "",       "0.005 1.0",  "Wheel steering rate proportional gain.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_WR_I",         0.1,  "",       "0.0 50.0",   "Wheel steering rate integrator gain.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_WR_IMAX",      1.0,  "",       "0.0 1.0",    "Wheel steering rate integrator limit.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_W_RMAX",       0.0,  "deg/s",  "0.0 90.0",   "Maximum wheel steering rate.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_RR_FF",        0.5,  "",       "0.0 10.0",   "Roll rate feed forward.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_PR_FF",        0.5,  "",       "0.0 10.0",   "Pitch rate feed forward.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_YR_FF",        0.3,  "",       "0.0 10.0",   "Yaw rate feed forward.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_WR_FF",        0.2,  "",       "0.0 10.0",   "Wheel steering rate feed forward.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_YCO_VMIN",     1000.0,"m/s",   "",           "Minimal speed for yaw coordination. Set very high to disable.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_YCO_METHOD",   0,    "",       "0 1",        "Method for yaw coordination. 0=open-loop, 1=closed-loop.", "FW Attitude Control", "INT32"),
    Parameter("FW_AIRSPD_MIN",   10.0, "m/s",    "0.0 40",     "Minimum airspeed. TECS increases aggressiveness below this.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_AIRSPD_TRIM",  15.0, "m/s",    "0.0 40",     "Trim airspeed. TECS tries to fly at this speed.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_AIRSPD_MAX",   20.0, "m/s",    "0.0 40",     "Maximum airspeed. TECS decreases aggressiveness above this.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_RSP_OFF",      0.0,  "deg",    "-90.0 90.0", "Roll setpoint offset in degrees.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_PSP_OFF",      0.0,  "deg",    "-90.0 90.0", "Pitch setpoint offset in degrees.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_MAN_R_MAX",    45.0, "deg",    "0.0 90.0",   "Max manual roll in attitude stabilized mode.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_MAN_P_MAX",    45.0, "deg",    "0.0 90.0",   "Max manual pitch in attitude stabilized mode.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_FLAPS_SCL",    1.0,  "",       "0.0 1.0",    "Scale factor for flaps.", "FW Attitude Control", "FLOAT"),
    Parameter("FW_FLAPERON_SCL", 0.0,  "",       "0.0 1.0",    "Scale factor for flaperons.", "FW Attitude Control", "FLOAT"),

    # ── Fixed Wing TECS ──────────────────────────────────────────────
    Parameter("FW_T_SINK_MIN",   2.0,  "",       "",           "Minimum descent rate with THR_MIN.", "Fixed Wing TECS", "FLOAT"),
    Parameter("FW_T_SINK_MAX",   5.0,  "",       "",           "Maximum descent rate. Too large may overspeed on descent.", "Fixed Wing TECS", "FLOAT"),
    Parameter("FW_T_TIME_CONST", 5.0,  "",       "",           "TECS time constant. Smaller=faster response.", "Fixed Wing TECS", "FLOAT"),
    Parameter("FW_T_THRO_CONST", 8.0,  "",       "",           "TECS throttle time constant.", "Fixed Wing TECS", "FLOAT"),
    Parameter("FW_T_THR_DAMP",   0.5,  "",       "",           "Throttle damping factor. Increase to add damping for speed/height oscillations.", "Fixed Wing TECS", "FLOAT"),
    Parameter("FW_T_INTEG_GAIN", 0.1,  "",       "",           "Integrator gain. Increase to trim out speed/height offsets faster.", "Fixed Wing TECS", "FLOAT"),
    Parameter("FW_T_VERT_ACC",   7.0,  "",       "",           "Maximum vertical acceleration (m/s^2). Default ~0.7g.", "Fixed Wing TECS", "FLOAT"),
    Parameter("FW_T_HGT_OMEGA",  3.0,  "",       "",           "Complementary filter omega for height. Higher=more baro trust.", "Fixed Wing TECS", "FLOAT"),
    Parameter("FW_T_SPD_OMEGA",  2.0,  "",       "",           "Complementary filter omega for speed. Higher=more airspeed sensor trust.", "Fixed Wing TECS", "FLOAT"),
    Parameter("FW_T_RLL2THR",    15.0, "",       "",           "Roll to throttle feed forward. Compensates drag in turns.", "Fixed Wing TECS", "FLOAT"),
    Parameter("FW_T_SPDWEIGHT",  1.0,  "",       "",           "Speed vs altitude priority. 0=altitude only, 2=speed only.", "Fixed Wing TECS", "FLOAT"),
    Parameter("FW_T_PTCH_DAMP",  0.0,  "",       "",           "Pitch damping factor.", "Fixed Wing TECS", "FLOAT"),
    Parameter("FW_T_HRATE_P",    0.05, "",       "",           "Height rate P factor.", "Fixed Wing TECS", "FLOAT"),
    Parameter("FW_T_HRATE_FF",   0.0,  "",       "",           "Height rate FF factor.", "Fixed Wing TECS", "FLOAT"),
    Parameter("FW_T_SRATE_P",    0.02, "",       "",           "Speed rate P factor.", "Fixed Wing TECS", "FLOAT"),

    # ── GPS Failure Navigation ───────────────────────────────────────
    Parameter("NAV_GPSF_LT",    30.0,  "s",      "0.0+",       "Loiter time before flight termination on GPS failure.", "GPS Failure Navigation", "FLOAT"),
    Parameter("NAV_GPSF_R",     15.0,  "deg",    "0.0 30.0",   "Open loop loiter roll angle in degrees.", "GPS Failure Navigation", "FLOAT"),
    Parameter("NAV_GPSF_P",     0.0,   "deg",    "-30.0 30.0", "Open loop loiter pitch angle in degrees.", "GPS Failure Navigation", "FLOAT"),
    Parameter("NAV_GPSF_TR",    0.7,   "",       "0.0 1.0",    "Open loop loiter thrust value.", "GPS Failure Navigation", "FLOAT"),

    # ── Geofence ─────────────────────────────────────────────────────
    Parameter("GF_ACTION",      1,     "",       "0 4",        "Geofence violation action. 0=none, 1=warn, 2=loiter, 3=RTL, 4=terminate.", "Geofence", "INT32"),
    Parameter("GF_ALTMODE",     0,     "",       "0 1",        "Geofence altitude mode. 0=WGS84, 1=AMSL.", "Geofence", "INT32"),
    Parameter("GF_SOURCE",      0,     "",       "0 1",        "Geofence source. 0=global position, 1=GPS.", "Geofence", "INT32"),
    Parameter("GF_COUNT",       -1,    "",       "-1 10",      "Geofence counter limit. Number of consecutive out-of-fence measurements to trigger.", "Geofence", "INT32"),
    Parameter("GF_MAX_HOR_DIST",-1,    "m",      "-1+",        "Max horizontal distance from home in meters. -1=disabled.", "Geofence", "INT32"),
    Parameter("GF_MAX_VER_DIST",-1,    "m",      "-1+",        "Max vertical distance from home in meters. -1=disabled.", "Geofence", "INT32"),

    # ── Gimbal ───────────────────────────────────────────────────────
    Parameter("GMB_USE_MNT",    0,     "",       "0 1",        "Consider mount operation mode. If 1, mount mode will be enforced.", "Gimbal", "INT32"),
    Parameter("GMB_AUX_MNT_CHN",0,    "",       "0 3",        "Auxiliary switch for mount operation mode. 0=disable manual mode control.", "Gimbal", "INT32"),

    # ── L1 Control ───────────────────────────────────────────────────
    Parameter("FW_L1_PERIOD",   20.0,  "",       "12.0 50.0",  "L1 period. Tracking point distance ahead of aircraft. 18-25m works for most.", "L1 Control", "FLOAT"),
    Parameter("FW_L1_DAMPING",  0.75,  "",       "0.6 0.9",    "L1 damping factor.", "L1 Control", "FLOAT"),
    Parameter("FW_THR_CRUISE",  0.6,   "",       "0.0 1.0",    "Cruise throttle. Throttle to achieve desired cruise speed.", "L1 Control", "FLOAT"),
    Parameter("FW_THR_SLEW_MAX",0.0,   "",       "0.0 1.0",    "Throttle max slew rate.", "L1 Control", "FLOAT"),
    Parameter("FW_P_LIM_MIN",   -45.0, "deg",    "-60.0 0.0",  "Negative pitch limit.", "L1 Control", "FLOAT"),
    Parameter("FW_P_LIM_MAX",   45.0,  "deg",    "0.0 60.0",   "Positive pitch limit.", "L1 Control", "FLOAT"),
    Parameter("FW_R_LIM",       50.0,  "deg",    "35.0 65.0",  "Controller roll limit.", "L1 Control", "FLOAT"),
    Parameter("FW_THR_MAX",     1.0,   "",       "0.0 1.0",    "Throttle limit max.", "L1 Control", "FLOAT"),
    Parameter("FW_THR_MIN",     0.0,   "",       "0.0 1.0",    "Throttle limit min.", "L1 Control", "FLOAT"),
    Parameter("FW_THR_IDLE",    0.15,  "",       "0.0 0.4",    "Idle throttle while on the ground.", "L1 Control", "FLOAT"),
    Parameter("FW_THR_LND_MAX", 1.0,   "",       "0.0 1.0",    "Throttle limit value before flare.", "L1 Control", "FLOAT"),
    Parameter("FW_CLMBOUT_DIFF",10.0,  "",       "0.0 150.0",  "Climbout altitude difference. Climb with max throttle until within this distance.", "L1 Control", "FLOAT"),
    Parameter("FW_T_CLMB_MAX",  5.0,   "",       "2.0 10.0",   "Maximum climb rate with THR_MAX.", "L1 Control", "FLOAT"),
    Parameter("FW_LND_ANG",     5.0,   "deg",    "1.0 15.0",   "Landing slope angle.", "L1 Control", "FLOAT"),
    Parameter("FW_LND_HVIRT",   10.0,  "",       "",           "FW_LND_HVIRT parameter.", "L1 Control", "FLOAT"),
    Parameter("FW_LND_FLALT",   8.0,   "m",      "0.0 25.0",   "Landing flare altitude relative to landing altitude.", "L1 Control", "FLOAT"),
    Parameter("FW_LND_TLALT",   -1.0,  "m",      "-1.0 30.0",  "Landing throttle limit altitude. -1=default (2/3 of flare altitude).", "L1 Control", "FLOAT"),
    Parameter("FW_LND_HHDIST",  15.0,  "m",      "0 30.0",     "Landing heading hold horizontal distance.", "L1 Control", "FLOAT"),
    Parameter("FW_LND_USETER",  0,     "",       "0 1",        "Enable terrain estimate during landing.", "L1 Control", "INT32"),
    Parameter("FW_FLARE_PMIN",  2.5,   "deg",    "0 15.0",     "Flare minimum pitch (positive=nose up).", "L1 Control", "FLOAT"),
    Parameter("FW_FLARE_PMAX",  15.0,  "deg",    "0 45.0",     "Flare maximum pitch (positive=nose up).", "L1 Control", "FLOAT"),
    Parameter("FW_AIRSPD_SCALE",1.3,   "",       "1.0 1.5",    "Landing airspeed scale factor. Target = FW_AIRSPD_MIN * this factor.", "L1 Control", "FLOAT"),

    # ── Land Detector ────────────────────────────────────────────────
    Parameter("LNDMC_Z_VEL_MAX",  0.70, "m/s",  "",           "Multicopter max climb rate in landed state.", "Land Detector", "FLOAT"),
    Parameter("LNDMC_XY_VEL_MAX", 1.50, "m/s",  "",           "Multicopter max horizontal velocity in landed state.", "Land Detector", "FLOAT"),
    Parameter("LNDMC_ROT_MAX",    20.0, "deg/s", "",           "Multicopter max rotation allowed in landed state.", "Land Detector", "FLOAT"),
    Parameter("LNDMC_THR_MAX",    0.15, "",      "0.1 0.5",    "Multicopter max throttle allowed in landed state.", "Land Detector", "FLOAT"),
    Parameter("LNDFW_VEL_XY_MAX", 5.0,  "m/s",  "0.5 10",     "Fixed-wing max horizontal velocity in landed state.", "Land Detector", "FLOAT"),
    Parameter("LNDFW_VEL_Z_MAX",  10.0, "m/s",  "5 20",       "Fixed-wing max climb rate in landed state.", "Land Detector", "FLOAT"),
    Parameter("LNDFW_VELI_MAX",   4.0,  "m/s",  "2 10",       "Fixed-wing max short-term velocity in landed state.", "Land Detector", "FLOAT"),
    Parameter("LNDFW_AIRSPD_MAX", 8.00, "m/s",  "4 20",       "Airspeed max in landed state.", "Land Detector", "FLOAT"),

    # ── Launch detection ─────────────────────────────────────────────
    Parameter("LAUN_ALL_ON",    0,     "",       "0 1",        "Enable launch detection.", "Launch detection", "INT32"),
    Parameter("LAUN_CAT_A",     30.0,  "",       "0+",         "Catapult accelerometer threshold. LAUN_CAT_A * LAUN_CAT_T = trigger threshold.", "Launch detection", "FLOAT"),
    Parameter("LAUN_CAT_T",     0.05,  "",       "0+",         "Catapult time threshold. LAUN_CAT_A * LAUN_CAT_T = trigger threshold.", "Launch detection", "FLOAT"),
    Parameter("LAUN_CAT_MDEL",  0.0,   "s",      "0+",         "Motor delay. Delay between attitude control start and throttle powerup.", "Launch detection", "FLOAT"),
    Parameter("LAUN_CAT_PMAX",  30.0,  "deg",    "0 45",       "Maximum pitch before throttle powers up during motor delay phase.", "Launch detection", "FLOAT"),

    # ── Local Position Estimator ─────────────────────────────────────
    Parameter("LPE_ENABLED",    1,     "",       "",           "Enable local position estimator.", "Local Position Estimator", "INT32"),
    Parameter("LPE_INTEGRATE",  1,     "",       "",           "Enable accelerometer integration for prediction.", "Local Position Estimator", "INT32"),
    Parameter("LPE_FLW_XY",     0.01,  "m",      "0.01 1",     "Optical flow xy standard deviation.", "Local Position Estimator", "FLOAT"),
    Parameter("LPE_SNR_Z",      0.2,   "m",      "0.01 1",     "Sonar z standard deviation.", "Local Position Estimator", "FLOAT"),
    Parameter("LPE_LDR_Z",      0.03,  "m",      "0.01 1",     "Lidar z standard deviation.", "Local Position Estimator", "FLOAT"),
    Parameter("LPE_ACC_XY",     0.0454,"m/s^2",  "0.00001 2",  "Accelerometer xy standard deviation.", "Local Position Estimator", "FLOAT"),
    Parameter("LPE_ACC_Z",      0.0454,"m/s^2",  "0.00001 2",  "Accelerometer z standard deviation.", "Local Position Estimator", "FLOAT"),
    Parameter("LPE_BAR_Z",      1.0,   "m",      "0.01 3",     "Barometric pressure altitude z standard deviation.", "Local Position Estimator", "FLOAT"),
    Parameter("LPE_GPS_XY",     2.0,   "m",      "0.01 5",     "GPS xy standard deviation.", "Local Position Estimator", "FLOAT"),
    Parameter("LPE_GPS_Z",      10.0,  "m",      "0.01 20",    "GPS z standard deviation.", "Local Position Estimator", "FLOAT"),
    Parameter("LPE_GPS_VXY",    0.275, "m/s",    "0.01 2",     "GPS xy velocity standard deviation.", "Local Position Estimator", "FLOAT"),
    Parameter("LPE_GPS_VZ",     0.237, "m/s",    "0.01 2",     "GPS z velocity standard deviation.", "Local Position Estimator", "FLOAT"),
    Parameter("LPE_EPH_MAX",    3.0,   "m",      "1.0 5.0",    "GPS max EPH.", "Local Position Estimator", "FLOAT"),
    Parameter("LPE_VIS_XY",     0.5,   "m",      "0.01 1",     "Vision xy standard deviation.", "Local Position Estimator", "FLOAT"),
    Parameter("LPE_VIS_Z",      0.5,   "m",      "0.01 2",     "Vision z standard deviation.", "Local Position Estimator", "FLOAT"),
    Parameter("LPE_NO_VISION",  0,     "",       "0 1",        "Circuit breaker to disable vision input. Set 328754 to disable.", "Local Position Estimator", "INT32"),
    Parameter("LPE_VIC_P",      0.05,  "m",      "0.01 1",     "Vicon position standard deviation.", "Local Position Estimator", "FLOAT"),
    Parameter("LPE_PN_P",       0.0,   "(m/s^2)-s","0 1",      "Position propagation process noise power.", "Local Position Estimator", "FLOAT"),
    Parameter("LPE_PN_V",       0.0,   "(m/s)-s","0 5",        "Velocity propagation process noise power.", "Local Position Estimator", "FLOAT"),
    Parameter("LPE_PN_B",       1e-8,  "(m/s)-s","0 1",        "Accel bias propagation process noise power.", "Local Position Estimator", "FLOAT"),
    Parameter("LPE_BETA_MAX",   1000.0,"",       "3 1000",     "Fault detection threshold for chi-squared distribution.", "Local Position Estimator", "FLOAT"),

    # ── MAVLink ──────────────────────────────────────────────────────
    Parameter("MAV_SYS_ID",     1,     "",       "1 250",      "MAVLink system ID.", "MAVLink", "INT32"),
    Parameter("MAV_COMP_ID",    1,     "",       "1 250",      "MAVLink component ID.", "MAVLink", "INT32"),
    Parameter("MAV_RADIO_ID",   0,     "",       "-1 240",     "MAVLink Radio ID. Non-zero attempts to configure the radio to this ID.", "MAVLink", "INT32"),
    Parameter("MAV_TYPE",       1,     "",       "1+",         "MAVLink airframe type.", "MAVLink", "INT32"),
    Parameter("MAV_USEHILGPS",  0,     "",       "",           "Use/Accept HIL GPS message even if not in HIL mode.", "MAVLink", "INT32"),
    Parameter("MAV_FWDEXTSP",   1,     "",       "",           "Forward external setpoint messages to controllers in offboard mode.", "MAVLink", "INT32"),
    Parameter("MAV_TEST_PAR",   1,     "",       "-1000 1000", "Test parameter for testing the parameter interface.", "MAVLink", "INT32"),

    # ── Mission ──────────────────────────────────────────────────────
    Parameter("MIS_TAKEOFF_ALT", 2.5,  "m",      "",           "Take-off altitude. System climbs to this altitude before going to first waypoint.", "Mission", "FLOAT"),
    Parameter("MIS_ONBOARD_EN",  1,    "",       "0 1",        "Enable persistent onboard mission storage.", "Mission", "INT32"),
    Parameter("MIS_DIST_1WP",    900,  "",       "0 1000",     "Max horizontal distance from home to first waypoint. 0=disabled.", "Mission", "FLOAT"),
    Parameter("MIS_ALTMODE",     1,    "",       "0 1",        "Altitude setpoint mode. 0=zero-order hold, 1=first-order hold.", "Mission", "INT32"),
    Parameter("MIS_YAWMODE",     1,    "",       "0 3",        "Yaw setpoint mode. 0=destination yaw, 1=next wp, 2=home, 3=away from home.", "Mission", "INT32"),
    Parameter("MIS_YAW_TMT",    -1.0,  "s",      "-1 20",      "Time waiting on target heading at waypoint. -1=disabled.", "Mission", "FLOAT"),
    Parameter("MIS_YAW_ERR",    12.0,  "deg",    "0 90",       "Max yaw error for waypoint heading acceptance.", "Mission", "FLOAT"),
    Parameter("NAV_LOITER_RAD",  50.0, "m",      "25 1000",    "Loiter radius for missions/RTL (fixed-wing only).", "Mission", "FLOAT"),
    Parameter("NAV_ACC_RAD",     10.0, "m",      "0.05 200.0", "Default acceptance radius for waypoints.", "Mission", "FLOAT"),
    Parameter("NAV_DLL_OBC",     0,    "",       "0 1",        "Set OBC mode for data link loss.", "Mission", "INT32"),
    Parameter("NAV_RCL_OBC",     0,    "",       "0 1",        "Set OBC mode for RC loss.", "Mission", "INT32"),

    # ── Multicopter Attitude Control ─────────────────────────────────
    Parameter("MC_ROLL_TC",      0.2,  "",       "0.15 0.25",  "Roll time constant. Reduce if too twitchy, increase if too sluggish.", "Multicopter Attitude Control", "FLOAT"),
    Parameter("MC_PITCH_TC",     0.2,  "",       "0.15 0.25",  "Pitch time constant. Reduce if too twitchy, increase if too sluggish.", "Multicopter Attitude Control", "FLOAT"),
    Parameter("MC_ROLL_P",       6.5,  "",       "0.0 8",      "Roll P gain. Desired angular speed in rad/s for 1 rad error.", "Multicopter Attitude Control", "FLOAT"),
    Parameter("MC_ROLLRATE_P",   0.15, "",       "0.0 0.5",    "Roll rate P gain.", "Multicopter Attitude Control", "FLOAT"),
    Parameter("MC_ROLLRATE_I",   0.05, "",       "0.0+",       "Roll rate I gain. Compensates static thrust difference or gravity center offset.", "Multicopter Attitude Control", "FLOAT"),
    Parameter("MC_ROLLRATE_D",   0.003,"",       "0.0 0.01",   "Roll rate D gain. Small values reduce fast oscillations.", "Multicopter Attitude Control", "FLOAT"),
    Parameter("MC_ROLLRATE_FF",  0.0,  "",       "0.0+",       "Roll rate feedforward. Improves tracking performance.", "Multicopter Attitude Control", "FLOAT"),
    Parameter("MC_PITCH_P",      6.5,  "1/s",    "0.0 10",     "Pitch P gain. Desired angular speed in rad/s for 1 rad error.", "Multicopter Attitude Control", "FLOAT"),
    Parameter("MC_PITCHRATE_P",  0.15, "",       "0.0 0.6",    "Pitch rate P gain.", "Multicopter Attitude Control", "FLOAT"),
    Parameter("MC_PITCHRATE_I",  0.05, "",       "0.0+",       "Pitch rate I gain.", "Multicopter Attitude Control", "FLOAT"),
    Parameter("MC_PITCHRATE_D",  0.003,"",       "0.0+",       "Pitch rate D gain. Small values reduce fast oscillations.", "Multicopter Attitude Control", "FLOAT"),
    Parameter("MC_PITCHRATE_FF", 0.0,  "",       "0.0+",       "Pitch rate feedforward. Improves tracking performance.", "Multicopter Attitude Control", "FLOAT"),
    Parameter("MC_YAW_P",        2.8,  "1/s",    "0.0 5",      "Yaw P gain. Desired angular speed in rad/s for 1 rad error.", "Multicopter Attitude Control", "FLOAT"),
    Parameter("MC_YAWRATE_P",    0.2,  "",       "0.0 0.6",    "Yaw rate P gain.", "Multicopter Attitude Control", "FLOAT"),
    Parameter("MC_YAWRATE_I",    0.1,  "",       "0.0+",       "Yaw rate I gain.", "Multicopter Attitude Control", "FLOAT"),
    Parameter("MC_YAWRATE_D",    0.0,  "",       "0.0+",       "Yaw rate D gain.", "Multicopter Attitude Control", "FLOAT"),
    Parameter("MC_YAWRATE_FF",   0.0,  "",       "0.0+",       "Yaw rate feedforward.", "Multicopter Attitude Control", "FLOAT"),
    Parameter("MC_YAW_FF",       0.5,  "",       "0.0 1.0",    "Yaw feed forward weight. 0=slow/no overshoot, 1=fast/big overshoot.", "Multicopter Attitude Control", "FLOAT"),
    Parameter("MC_ROLLRATE_MAX", 220.0,"deg/s",  "0.0 360.0",  "Max roll rate limit.", "Multicopter Attitude Control", "FLOAT"),
    Parameter("MC_PITCHRATE_MAX",220.0,"deg/s",  "0.0 360.0",  "Max pitch rate limit.", "Multicopter Attitude Control", "FLOAT"),
    Parameter("MC_YAWRATE_MAX",  200.0,"deg/s",  "0.0 360.0",  "Max yaw rate. Values significantly over 120 deg/s may cause mixer saturation.", "Multicopter Attitude Control", "FLOAT"),
    Parameter("MC_YAWRAUTO_MAX", 45.0, "deg/s",  "0.0 120.0",  "Max yaw rate in auto mode. 30 deg/s recommended to avoid twitching.", "Multicopter Attitude Control", "FLOAT"),
    Parameter("MC_ACRO_R_MAX",   360.0,"deg/s",  "0.0 1000.0", "Max acro roll rate.", "Multicopter Attitude Control", "FLOAT"),
    Parameter("MC_ACRO_P_MAX",   360.0,"deg/s",  "0.0 1000.0", "Max acro pitch rate.", "Multicopter Attitude Control", "FLOAT"),
    Parameter("MC_ACRO_Y_MAX",   360.0,"deg/s",  "0.0 1000.0", "Max acro yaw rate.", "Multicopter Attitude Control", "FLOAT"),
    Parameter("MC_RATT_TH",      1.0,  "",       "0.0 1.0",    "Threshold for Rattitude mode manual input.", "Multicopter Attitude Control", "FLOAT"),

    # ── Multicopter Position Control ─────────────────────────────────
    Parameter("MPC_THR_MIN",     0.12, "",       "0.05 1.0",   "Minimum thrust in auto thrust control. Set >0 to avoid free fall.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_THR_HOVER",   0.5,  "",       "0.2 0.8",    "Hover thrust. Vertical thrust required to hover.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_ALTCTL_DZ",   0.1,  "",       "0.0 0.2",    "ALTCTL throttle curve deadband halfwidth.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_ALTCTL_DY",   0.0,  "",       "0.0 0.2",    "ALTCTL throttle curve breakpoint height.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_THR_MAX",     0.9,  "",       "0.0 0.95",   "Maximum thrust in auto thrust control. 0.8-0.9 recommended.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_MANTHR_MIN",  0.08, "",       "0.0 1.0",    "Minimum manual thrust. Set >0 to avoid free fall.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_MANTHR_MAX",  0.9,  "",       "0.0 1.0",    "Maximum manual thrust. 0.8-0.9 recommended.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_Z_P",         1.0,  "",       "0.0+",       "Proportional gain for vertical position error.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_Z_VEL_P",     0.2,  "",       "0.0+",       "Proportional gain for vertical velocity error.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_Z_VEL_I",     0.02, "",       "0.0+",       "Integral gain for vertical velocity. Allows hover thrust estimation.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_Z_VEL_D",     0.0,  "",       "0.0+",       "Differential gain for vertical velocity error.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_Z_VEL_MAX",   3.0,  "m/s",    "0.0 8.0",    "Maximum vertical velocity in AUTO mode.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_Z_FF",        0.5,  "",       "0.0 1.0",    "Vertical velocity feed forward. 0=slow, 1=fast.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_XY_P",        1.0,  "",       "0.0+",       "Proportional gain for horizontal position error.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_XY_VEL_P",    0.1,  "",       "0.0+",       "Proportional gain for horizontal velocity error.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_XY_VEL_I",    0.02, "",       "0.0+",       "Integral gain for horizontal velocity. Allows resisting wind.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_XY_VEL_D",    0.01, "",       "0.0+",       "Differential gain for horizontal velocity.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_XY_VEL_MAX",  5.0,  "m/s",    "0.0+",       "Maximum horizontal velocity in AUTO mode.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_XY_FF",       0.5,  "",       "0.0 1.0",    "Horizontal velocity feed forward.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_TILTMAX_AIR", 45.0, "deg",    "0.0 90.0",   "Maximum tilt angle in air (AUTO and POSCTRL).", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_TILTMAX_LND", 12.0, "deg",    "0.0 90.0",   "Maximum tilt during landing.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_LAND_SPEED",  0.5,  "m/s",    "0.0+",       "Landing descend rate.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_TKO_SPEED",   1.5,  "m/s",    "0.0+",       "Takeoff climb rate.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_MAN_R_MAX",   35.0, "deg",    "0.0 90.0",   "Max manual roll.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_MAN_P_MAX",   35.0, "deg",    "0.0 90.0",   "Max manual pitch.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_MAN_Y_MAX",   200.0,"deg/s",  "0.0+",       "Max manual yaw rate.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_HOLD_XY_DZ",  0.1,  "%",      "0.0 1.0",    "Deadzone of X,Y sticks where position hold is enabled.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_HOLD_MAX_XY", 0.8,  "m/s",    "0.0+",       "Maximum horizontal velocity for position hold. 0=disable check.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_HOLD_MAX_Z",  0.6,  "m/s",    "0.0+",       "Maximum vertical velocity for position hold. 0=disable check.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_VELD_LP",     5.0,  "Hz",     "0.0+",       "Low pass filter cutoff for numerical velocity derivative.", "Multicopter Position Control", "FLOAT"),
    Parameter("MPC_ACC_HOR_MAX", 6.0,  "m/s/s",  "2.0 10.0",   "Maximum horizontal acceleration in velocity controlled modes.", "Multicopter Position Control", "FLOAT"),

    # ── PWM Outputs ──────────────────────────────────────────────────
    Parameter("PWM_AUX_REV1",   0,     "",       "0 1",        "Invert direction of AUX output channel 1. Requires reboot.", "PWM Outputs", "INT32"),
    Parameter("PWM_AUX_REV2",   0,     "",       "0 1",        "Invert direction of AUX output channel 2. Requires reboot.", "PWM Outputs", "INT32"),
    Parameter("PWM_AUX_REV3",   0,     "",       "0 1",        "Invert direction of AUX output channel 3. Requires reboot.", "PWM Outputs", "INT32"),
    Parameter("PWM_AUX_REV4",   0,     "",       "0 1",        "Invert direction of AUX output channel 4. Requires reboot.", "PWM Outputs", "INT32"),
    Parameter("PWM_AUX_REV5",   0,     "",       "0 1",        "Invert direction of AUX output channel 5. Requires reboot.", "PWM Outputs", "INT32"),
    Parameter("PWM_AUX_REV6",   0,     "",       "0 1",        "Invert direction of AUX output channel 6. Requires reboot.", "PWM Outputs", "INT32"),
    Parameter("PWM_MAIN_REV1",  0,     "",       "0 1",        "Invert direction of MAIN output channel 1. Requires reboot.", "PWM Outputs", "INT32"),
    Parameter("PWM_MAIN_REV2",  0,     "",       "0 1",        "Invert direction of MAIN output channel 2. Requires reboot.", "PWM Outputs", "INT32"),
    Parameter("PWM_MAIN_REV3",  0,     "",       "0 1",        "Invert direction of MAIN output channel 3. Requires reboot.", "PWM Outputs", "INT32"),
    Parameter("PWM_MAIN_REV4",  0,     "",       "0 1",        "Invert direction of MAIN output channel 4. Requires reboot.", "PWM Outputs", "INT32"),
    Parameter("PWM_MAIN_REV5",  0,     "",       "0 1",        "Invert direction of MAIN output channel 5. Requires reboot.", "PWM Outputs", "INT32"),
    Parameter("PWM_MAIN_REV6",  0,     "",       "0 1",        "Invert direction of MAIN output channel 6. Requires reboot.", "PWM Outputs", "INT32"),
    Parameter("PWM_MAIN_REV7",  0,     "",       "0 1",        "Invert direction of MAIN output channel 7. Requires reboot.", "PWM Outputs", "INT32"),
    Parameter("PWM_MAIN_REV8",  0,     "",       "0 1",        "Invert direction of MAIN output channel 8. Requires reboot.", "PWM Outputs", "INT32"),
    Parameter("PWM_SBUS_MODE",  0,     "",       "0 1",        "Enable S.BUS out instead of RSSI.", "PWM Outputs", "INT32"),
    Parameter("PWM_MIN",        1000,  "us",     "800 1400",   "Minimum PWM for MAIN outputs. REQUIRES FULL REBOOT.", "PWM Outputs", "INT32"),
    Parameter("PWM_MAX",        2000,  "us",     "1600 2200",  "Maximum PWM for MAIN outputs. REQUIRES FULL REBOOT.", "PWM Outputs", "INT32"),
    Parameter("PWM_DISARMED",   0,     "us",     "0 2200",     "Disarmed PWM for MAIN outputs. REQUIRES FULL REBOOT.", "PWM Outputs", "INT32"),
    Parameter("PWM_AUX_MIN",    1000,  "us",     "800 1400",   "Minimum PWM for AUX outputs. REQUIRES FULL REBOOT.", "PWM Outputs", "INT32"),
    Parameter("PWM_AUX_MAX",    2000,  "us",     "1600 2200",  "Maximum PWM for AUX outputs. REQUIRES FULL REBOOT.", "PWM Outputs", "INT32"),
    Parameter("PWM_AUX_DISARMED",1000, "us",     "0 2200",     "Disarmed PWM for AUX outputs. REQUIRES FULL REBOOT.", "PWM Outputs", "INT32"),

    # ── Return To Land ───────────────────────────────────────────────
    Parameter("RTL_RETURN_ALT",  60,   "m",      "0 150",      "RTL altitude in meters.", "Return To Land", "FLOAT"),
    Parameter("RTL_DESCEND_ALT", 30,   "m",      "2 100",      "RTL loiter altitude above home before landing.", "Return To Land", "FLOAT"),
    Parameter("RTL_LAND_DELAY",  -1.0, "s",      "-1 300",     "RTL delay before landing. -1=loiter indefinitely.", "Return To Land", "FLOAT"),

    # ── Runway Takeoff ───────────────────────────────────────────────
    Parameter("RWTO_TKOFF",     0,     "",       "0 1",        "Enable runway takeoff with landing gear.", "Runway Takeoff", "INT32"),
    Parameter("RWTO_HDG",       0,     "",       "0 1",        "Heading during runway takeoff. 0=airframe, 1=towards waypoint.", "Runway Takeoff", "INT32"),
    Parameter("RWTO_NAV_ALT",   5.0,   "m",      "0.0 100.0",  "Altitude AGL for sufficient ground clearance to allow roll.", "Runway Takeoff", "FLOAT"),
    Parameter("RWTO_MAX_THR",   1.0,   "",       "0.0 1.0",    "Max throttle during runway takeoff.", "Runway Takeoff", "FLOAT"),
    Parameter("RWTO_PSP",       0.0,   "deg",    "0.0 20.0",   "Pitch setpoint during taxi / before takeoff airspeed.", "Runway Takeoff", "FLOAT"),
    Parameter("RWTO_MAX_PITCH", 20.0,  "deg",    "0.0 60.0",   "Max pitch during takeoff.", "Runway Takeoff", "FLOAT"),
    Parameter("RWTO_MAX_ROLL",  25.0,  "deg",    "0.0 60.0",   "Max roll during climbout.", "Runway Takeoff", "FLOAT"),
    Parameter("RWTO_AIRSPD_SCL",1.3,   "",       "0.0 2.0",    "Min airspeed scaling for takeoff. Pitch up when FW_AIRSPD_MIN * this is reached.", "Runway Takeoff", "FLOAT"),

    # ── SD Logging ───────────────────────────────────────────────────
    Parameter("SDLOG_RATE",     -1,    "",       "-1 100",     "Logging rate. -1=use cmdline, 0=minimum, other=Hz.", "SD Logging", "INT32"),
    Parameter("SDLOG_EXT",      -1,    "",       "-1 1",       "Enable extended logging mode. -1=cmdline, 0=disabled, 1=enabled.", "SD Logging", "INT32"),
    Parameter("SDLOG_GPSTIME",  1,     "",       "0 1",        "Use timestamps only if GPS 3D fix is available.", "SD Logging", "INT32"),
    Parameter("SDLOG_UTC_OFFSET",0,    "min",    "-1000 1000", "UTC offset in minutes (e.g. UTC+09:00 = 540).", "SD Logging", "INT32"),
    Parameter("SDLOG_PRIO_BOOST",0,    "",       "0 3",        "Give logging app higher thread priority to avoid data loss.", "SD Logging", "INT32"),

    # ── UAVCAN ───────────────────────────────────────────────────────
    Parameter("UAVCAN_ENABLE",  0,     "",       "0 3",        "Enable UAVCAN. 0=disabled, 1=actuators+sensors, 2=+dynamic alloc, 3=+motor control.", "UAVCAN", "INT32"),
    Parameter("UAVCAN_NODE_ID", 1,     "",       "1 125",      "UAVCAN Node ID.", "UAVCAN", "INT32"),
    Parameter("UAVCAN_BITRATE", 1000000,"",      "20000 1000000","UAVCAN CAN bus bitrate.", "UAVCAN", "INT32"),

    # ── VTOL Attitude Control ────────────────────────────────────────
    Parameter("VT_TRANS_THR",   0.6,   "",       "0.0 1.0",    "Target throttle for pusher/puller motor during transition to FW mode.", "VTOL Attitude Control", "FLOAT"),
    Parameter("VT_TILT_MC",     0.0,   "",       "0.0 1",      "Position of tilt servo in multicopter mode.", "VTOL Attitude Control", "FLOAT"),
    Parameter("VT_TILT_TRANS",  0.3,   "",       "0.0 1",      "Position of tilt servo in transition mode.", "VTOL Attitude Control", "FLOAT"),
    Parameter("VT_TILT_FW",     1.0,   "",       "0.0 1",      "Position of tilt servo in fixed-wing mode.", "VTOL Attitude Control", "FLOAT"),
    Parameter("VT_TRANS_P2_DUR",0.5,   "s",      "0.1 2",      "Duration of front transition phase 2 in seconds.", "VTOL Attitude Control", "FLOAT"),
    Parameter("VT_FW_MOT_OFFID",0,     "",       "0 12345678", "Channel number of motors to turn off in fixed-wing mode.", "VTOL Attitude Control", "INT32"),
    Parameter("VT_MOT_COUNT",   0,     "",       "0+",         "VTOL number of engines.", "VTOL Attitude Control", "INT32"),
    Parameter("VT_IDLE_PWM_MC", 900,   "",       "900+",       "Idle speed of VTOL when in multicopter mode.", "VTOL Attitude Control", "INT32"),
    Parameter("VT_MC_ARSPD_MIN",10.0,  "",       "0.0+",       "Minimum airspeed in multicopter mode.", "VTOL Attitude Control", "FLOAT"),
    Parameter("VT_MC_ARSPD_MAX",30.0,  "",       "0.0+",       "Maximum airspeed in multicopter mode.", "VTOL Attitude Control", "FLOAT"),
    Parameter("VT_MC_ARSPD_TRIM",10.0, "",       "0.0+",       "Trim airspeed in multicopter mode.", "VTOL Attitude Control", "FLOAT"),
    Parameter("VT_FW_PERM_STAB",0,     "",       "0 1",        "Permanent stabilization in FW mode.", "VTOL Attitude Control", "INT32"),
    Parameter("VT_FW_PITCH_TRIM",0.0,  "",       "-1 1",       "Fixed-wing pitch trim (neutral elevon adjustment).", "VTOL Attitude Control", "FLOAT"),
    Parameter("VT_POWER_MAX",   120.0, "",       "1+",         "Motor max power in watts.", "VTOL Attitude Control", "FLOAT"),
    Parameter("VT_PROP_EFF",    0.0,   "",       "0.0 0.9",    "Propeller efficiency parameter.", "VTOL Attitude Control", "FLOAT"),
    Parameter("VT_ARSP_LP_GAIN",0.3,   "",       "0.0 0.99",   "Total airspeed estimate low-pass filter gain.", "VTOL Attitude Control", "FLOAT"),
    Parameter("VT_TYPE",        0,     "",       "0 2",        "VTOL Type. 0=Tailsitter, 1=Tiltrotor, 2=Standard.", "VTOL Attitude Control", "INT32"),
    Parameter("VT_ELEV_MC_LOCK",0,     "",       "0 1",        "Lock elevons in multicopter mode.", "VTOL Attitude Control", "INT32"),
    Parameter("VT_F_TRANS_DUR", 3.0,   "s",      "0.0 5",      "Duration of front transition in seconds.", "VTOL Attitude Control", "FLOAT"),
    Parameter("VT_B_TRANS_DUR", 2.0,   "s",      "0.0 5",      "Duration of back transition in seconds.", "VTOL Attitude Control", "FLOAT"),
    Parameter("VT_ARSP_BLEND",  8.0,   "",       "0.0 20.0",   "Transition blending airspeed. 0=disabled.", "VTOL Attitude Control", "FLOAT"),
    Parameter("VT_ARSP_TRANS",  10.0,  "",       "1.0 20",     "Transition airspeed for switching to FW mode.", "VTOL Attitude Control", "FLOAT"),
    Parameter("VT_OPT_RECOV_EN",0,     "",       "0 1",        "Enable optimal recovery strategy for pitch-weak tailsitters.", "VTOL Attitude Control", "INT32"),
    Parameter("VT_WV_LND_EN",   0,     "",       "0 1",        "Enable weather-vane mode for mission landings.", "VTOL Attitude Control", "INT32"),
    Parameter("VT_WV_YAWR_SCL", 0.15,  "",       "0 1",        "Weather-vane yaw rate scale to avoid fighting the wind.", "VTOL Attitude Control", "FLOAT"),
    Parameter("VT_WV_LTR_EN",   0,     "",       "0 1",        "Enable weather-vane mode for loiter.", "VTOL Attitude Control", "INT32"),
    Parameter("VT_TRANS_TIMEOUT",15.0, "s",      "0.0 30.0",   "Front transition timeout. 0=disabled.", "VTOL Attitude Control", "FLOAT"),

    # ── Radio Signal Loss ────────────────────────────────────────────
    Parameter("NAV_RCL_LT",    120.0,  "s",      "-1.0+",      "Loiter time before flight termination on RC signal loss. -1=skip loiter.", "Radio Signal Loss", "FLOAT"),
]

def get_default_params():
    """Always return a fresh deep copy so resets work cleanly."""
    return copy.deepcopy(DEFAULT_PARAMS)

def get_groups():
    """Return sorted list of unique group names."""
    return sorted(set(p.group for p in DEFAULT_PARAMS))